<?php
return array (
  'site_title' => 'Pure Comments',
  'site_tagline' => 'A simple commenting system for the small web.',
  'site_description' => 'Pure Comments is a simple, lightweight commenting system designed for the small web.',
  'site_email' => '',
  'custom_nav' => 'GitHub | https://github.com/kevquirk/purecomments',
  'custom_routes' => '',
  'head_inject_page' => '',
  'head_inject_post' => '',
  'footer_inject_page' => '',
  'footer_inject_post' => '',
  'posts_per_page' => 20,
  'search_excerpt_length' => 2500,
  'homepage_slug' => 'pure-comments',
  'blog_page_slug' => '__hidden__',
  'search_page_slug' => '',
  'search_page_notified' => true,
  'base_url' => 'https://comments.purecommons.org',
  'language' => 'en',
  'timezone' => 'UTC',
  'date_format' => 'F j, Y',
  'admin_username' => 'bfetbntrn',
  'admin_password_hash' => '$2y$10$AGLqnuhO7q0L1ggBQLO5c.lex5fLIRow4cjCjGt3qyRd5uFNOny8.',
  'cache' => 
  array (
    'enabled' => true,
    'rss_ttl' => 3600,
  ),
  'theme' => 
  array (
    'color_mode' => 'auto',
    'font_stack' => 'sans',
    'admin_font_stack' => 'mono',
    'admin_color_mode' => 'auto',
    'background_color' => '#FAFAFA',
    'text_color' => '#333',
    'accent_color' => '#0D47A1',
    'border_color' => '#333',
    'accent_bg_color' => '#EEE',
    'background_color_dark' => '#222',
    'text_color_dark' => '#DCDCDC',
    'accent_color_dark' => '#88C0D0',
    'border_color_dark' => '#DCDCDC',
    'accent_bg_color_dark' => '#1A1A1A',
    'post_list_layout' => 'excerpt',
  ),
  'assets' => 
  array (
    'favicon' => '/content/images/favicon.png',
    'og_image' => '/assets/images/og-image.png',
    'og_image_preferred' => 'banner',
  ),
  'hide_homepage_title' => true,
  'hide_blog_page_title' => true,
  'admin_homepage' => 'content',
  'admin_hide_dashboard' => false,
);
